// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userService.proto

package com.user.grpc;

public final class UserService {
  private UserService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocProofReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocProofReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 proverID = 1;</code>
     */
    int getProverID();

    /**
     * <code>int32 epoch = 2;</code>
     */
    int getEpoch();

    /**
     * <code>.Position loc = 3;</code>
     */
    boolean hasLoc();
    /**
     * <code>.Position loc = 3;</code>
     */
    com.user.grpc.UserService.Position getLoc();
    /**
     * <code>.Position loc = 3;</code>
     */
    com.user.grpc.UserService.PositionOrBuilder getLocOrBuilder();

    /**
     * <code>string dig_sign = 4;</code>
     */
    java.lang.String getDigSign();
    /**
     * <code>string dig_sign = 4;</code>
     */
    com.google.protobuf.ByteString
        getDigSignBytes();
  }
  /**
   * Protobuf type {@code LocProofReq}
   */
  public  static final class LocProofReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocProofReq)
      LocProofReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocProofReq.newBuilder() to construct.
    private LocProofReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocProofReq() {
      proverID_ = 0;
      epoch_ = 0;
      digSign_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocProofReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              proverID_ = input.readInt32();
              break;
            }
            case 16: {

              epoch_ = input.readInt32();
              break;
            }
            case 26: {
              com.user.grpc.UserService.Position.Builder subBuilder = null;
              if (loc_ != null) {
                subBuilder = loc_.toBuilder();
              }
              loc_ = input.readMessage(com.user.grpc.UserService.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loc_);
                loc_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              digSign_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.user.grpc.UserService.internal_static_LocProofReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.user.grpc.UserService.internal_static_LocProofReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.user.grpc.UserService.LocProofReq.class, com.user.grpc.UserService.LocProofReq.Builder.class);
    }

    public static final int PROVERID_FIELD_NUMBER = 1;
    private int proverID_;
    /**
     * <code>int32 proverID = 1;</code>
     */
    public int getProverID() {
      return proverID_;
    }

    public static final int EPOCH_FIELD_NUMBER = 2;
    private int epoch_;
    /**
     * <code>int32 epoch = 2;</code>
     */
    public int getEpoch() {
      return epoch_;
    }

    public static final int LOC_FIELD_NUMBER = 3;
    private com.user.grpc.UserService.Position loc_;
    /**
     * <code>.Position loc = 3;</code>
     */
    public boolean hasLoc() {
      return loc_ != null;
    }
    /**
     * <code>.Position loc = 3;</code>
     */
    public com.user.grpc.UserService.Position getLoc() {
      return loc_ == null ? com.user.grpc.UserService.Position.getDefaultInstance() : loc_;
    }
    /**
     * <code>.Position loc = 3;</code>
     */
    public com.user.grpc.UserService.PositionOrBuilder getLocOrBuilder() {
      return getLoc();
    }

    public static final int DIG_SIGN_FIELD_NUMBER = 4;
    private volatile java.lang.Object digSign_;
    /**
     * <code>string dig_sign = 4;</code>
     */
    public java.lang.String getDigSign() {
      java.lang.Object ref = digSign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digSign_ = s;
        return s;
      }
    }
    /**
     * <code>string dig_sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDigSignBytes() {
      java.lang.Object ref = digSign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (proverID_ != 0) {
        output.writeInt32(1, proverID_);
      }
      if (epoch_ != 0) {
        output.writeInt32(2, epoch_);
      }
      if (loc_ != null) {
        output.writeMessage(3, getLoc());
      }
      if (!getDigSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, digSign_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (proverID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, proverID_);
      }
      if (epoch_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, epoch_);
      }
      if (loc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoc());
      }
      if (!getDigSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, digSign_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.user.grpc.UserService.LocProofReq)) {
        return super.equals(obj);
      }
      com.user.grpc.UserService.LocProofReq other = (com.user.grpc.UserService.LocProofReq) obj;

      boolean result = true;
      result = result && (getProverID()
          == other.getProverID());
      result = result && (getEpoch()
          == other.getEpoch());
      result = result && (hasLoc() == other.hasLoc());
      if (hasLoc()) {
        result = result && getLoc()
            .equals(other.getLoc());
      }
      result = result && getDigSign()
          .equals(other.getDigSign());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROVERID_FIELD_NUMBER;
      hash = (53 * hash) + getProverID();
      hash = (37 * hash) + EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + getEpoch();
      if (hasLoc()) {
        hash = (37 * hash) + LOC_FIELD_NUMBER;
        hash = (53 * hash) + getLoc().hashCode();
      }
      hash = (37 * hash) + DIG_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getDigSign().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.user.grpc.UserService.LocProofReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.user.grpc.UserService.LocProofReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocProofReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocProofReq)
        com.user.grpc.UserService.LocProofReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.user.grpc.UserService.internal_static_LocProofReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.user.grpc.UserService.internal_static_LocProofReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.user.grpc.UserService.LocProofReq.class, com.user.grpc.UserService.LocProofReq.Builder.class);
      }

      // Construct using com.user.grpc.UserService.LocProofReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        proverID_ = 0;

        epoch_ = 0;

        if (locBuilder_ == null) {
          loc_ = null;
        } else {
          loc_ = null;
          locBuilder_ = null;
        }
        digSign_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.user.grpc.UserService.internal_static_LocProofReq_descriptor;
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofReq getDefaultInstanceForType() {
        return com.user.grpc.UserService.LocProofReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofReq build() {
        com.user.grpc.UserService.LocProofReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofReq buildPartial() {
        com.user.grpc.UserService.LocProofReq result = new com.user.grpc.UserService.LocProofReq(this);
        result.proverID_ = proverID_;
        result.epoch_ = epoch_;
        if (locBuilder_ == null) {
          result.loc_ = loc_;
        } else {
          result.loc_ = locBuilder_.build();
        }
        result.digSign_ = digSign_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.user.grpc.UserService.LocProofReq) {
          return mergeFrom((com.user.grpc.UserService.LocProofReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.user.grpc.UserService.LocProofReq other) {
        if (other == com.user.grpc.UserService.LocProofReq.getDefaultInstance()) return this;
        if (other.getProverID() != 0) {
          setProverID(other.getProverID());
        }
        if (other.getEpoch() != 0) {
          setEpoch(other.getEpoch());
        }
        if (other.hasLoc()) {
          mergeLoc(other.getLoc());
        }
        if (!other.getDigSign().isEmpty()) {
          digSign_ = other.digSign_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.user.grpc.UserService.LocProofReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.user.grpc.UserService.LocProofReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int proverID_ ;
      /**
       * <code>int32 proverID = 1;</code>
       */
      public int getProverID() {
        return proverID_;
      }
      /**
       * <code>int32 proverID = 1;</code>
       */
      public Builder setProverID(int value) {
        
        proverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 proverID = 1;</code>
       */
      public Builder clearProverID() {
        
        proverID_ = 0;
        onChanged();
        return this;
      }

      private int epoch_ ;
      /**
       * <code>int32 epoch = 2;</code>
       */
      public int getEpoch() {
        return epoch_;
      }
      /**
       * <code>int32 epoch = 2;</code>
       */
      public Builder setEpoch(int value) {
        
        epoch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 epoch = 2;</code>
       */
      public Builder clearEpoch() {
        
        epoch_ = 0;
        onChanged();
        return this;
      }

      private com.user.grpc.UserService.Position loc_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.user.grpc.UserService.Position, com.user.grpc.UserService.Position.Builder, com.user.grpc.UserService.PositionOrBuilder> locBuilder_;
      /**
       * <code>.Position loc = 3;</code>
       */
      public boolean hasLoc() {
        return locBuilder_ != null || loc_ != null;
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public com.user.grpc.UserService.Position getLoc() {
        if (locBuilder_ == null) {
          return loc_ == null ? com.user.grpc.UserService.Position.getDefaultInstance() : loc_;
        } else {
          return locBuilder_.getMessage();
        }
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public Builder setLoc(com.user.grpc.UserService.Position value) {
        if (locBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loc_ = value;
          onChanged();
        } else {
          locBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public Builder setLoc(
          com.user.grpc.UserService.Position.Builder builderForValue) {
        if (locBuilder_ == null) {
          loc_ = builderForValue.build();
          onChanged();
        } else {
          locBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public Builder mergeLoc(com.user.grpc.UserService.Position value) {
        if (locBuilder_ == null) {
          if (loc_ != null) {
            loc_ =
              com.user.grpc.UserService.Position.newBuilder(loc_).mergeFrom(value).buildPartial();
          } else {
            loc_ = value;
          }
          onChanged();
        } else {
          locBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public Builder clearLoc() {
        if (locBuilder_ == null) {
          loc_ = null;
          onChanged();
        } else {
          loc_ = null;
          locBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public com.user.grpc.UserService.Position.Builder getLocBuilder() {
        
        onChanged();
        return getLocFieldBuilder().getBuilder();
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      public com.user.grpc.UserService.PositionOrBuilder getLocOrBuilder() {
        if (locBuilder_ != null) {
          return locBuilder_.getMessageOrBuilder();
        } else {
          return loc_ == null ?
              com.user.grpc.UserService.Position.getDefaultInstance() : loc_;
        }
      }
      /**
       * <code>.Position loc = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.user.grpc.UserService.Position, com.user.grpc.UserService.Position.Builder, com.user.grpc.UserService.PositionOrBuilder> 
          getLocFieldBuilder() {
        if (locBuilder_ == null) {
          locBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.user.grpc.UserService.Position, com.user.grpc.UserService.Position.Builder, com.user.grpc.UserService.PositionOrBuilder>(
                  getLoc(),
                  getParentForChildren(),
                  isClean());
          loc_ = null;
        }
        return locBuilder_;
      }

      private java.lang.Object digSign_ = "";
      /**
       * <code>string dig_sign = 4;</code>
       */
      public java.lang.String getDigSign() {
        java.lang.Object ref = digSign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digSign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dig_sign = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDigSignBytes() {
        java.lang.Object ref = digSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dig_sign = 4;</code>
       */
      public Builder setDigSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dig_sign = 4;</code>
       */
      public Builder clearDigSign() {
        
        digSign_ = getDefaultInstance().getDigSign();
        onChanged();
        return this;
      }
      /**
       * <code>string dig_sign = 4;</code>
       */
      public Builder setDigSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digSign_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocProofReq)
    }

    // @@protoc_insertion_point(class_scope:LocProofReq)
    private static final com.user.grpc.UserService.LocProofReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.user.grpc.UserService.LocProofReq();
    }

    public static com.user.grpc.UserService.LocProofReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocProofReq>
        PARSER = new com.google.protobuf.AbstractParser<LocProofReq>() {
      @java.lang.Override
      public LocProofReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocProofReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocProofReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocProofReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.user.grpc.UserService.LocProofReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocProofRepOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocProofRep)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string proof = 2;</code>
     */
    java.lang.String getProof();
    /**
     * <code>string proof = 2;</code>
     */
    com.google.protobuf.ByteString
        getProofBytes();

    /**
     * <code>string proof_dig_sig = 3;</code>
     */
    java.lang.String getProofDigSig();
    /**
     * <code>string proof_dig_sig = 3;</code>
     */
    com.google.protobuf.ByteString
        getProofDigSigBytes();

    /**
     * <code>int32 witnessID = 5;</code>
     */
    int getWitnessID();
  }
  /**
   * Protobuf type {@code LocProofRep}
   */
  public  static final class LocProofRep extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocProofRep)
      LocProofRepOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocProofRep.newBuilder() to construct.
    private LocProofRep(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocProofRep() {
      proof_ = "";
      proofDigSig_ = "";
      witnessID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocProofRep(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              proof_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              proofDigSig_ = s;
              break;
            }
            case 40: {

              witnessID_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.user.grpc.UserService.internal_static_LocProofRep_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.user.grpc.UserService.internal_static_LocProofRep_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.user.grpc.UserService.LocProofRep.class, com.user.grpc.UserService.LocProofRep.Builder.class);
    }

    public static final int PROOF_FIELD_NUMBER = 2;
    private volatile java.lang.Object proof_;
    /**
     * <code>string proof = 2;</code>
     */
    public java.lang.String getProof() {
      java.lang.Object ref = proof_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proof_ = s;
        return s;
      }
    }
    /**
     * <code>string proof = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProofBytes() {
      java.lang.Object ref = proof_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROOF_DIG_SIG_FIELD_NUMBER = 3;
    private volatile java.lang.Object proofDigSig_;
    /**
     * <code>string proof_dig_sig = 3;</code>
     */
    public java.lang.String getProofDigSig() {
      java.lang.Object ref = proofDigSig_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proofDigSig_ = s;
        return s;
      }
    }
    /**
     * <code>string proof_dig_sig = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProofDigSigBytes() {
      java.lang.Object ref = proofDigSig_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proofDigSig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WITNESSID_FIELD_NUMBER = 5;
    private int witnessID_;
    /**
     * <code>int32 witnessID = 5;</code>
     */
    public int getWitnessID() {
      return witnessID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProofBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, proof_);
      }
      if (!getProofDigSigBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, proofDigSig_);
      }
      if (witnessID_ != 0) {
        output.writeInt32(5, witnessID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProofBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, proof_);
      }
      if (!getProofDigSigBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, proofDigSig_);
      }
      if (witnessID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, witnessID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.user.grpc.UserService.LocProofRep)) {
        return super.equals(obj);
      }
      com.user.grpc.UserService.LocProofRep other = (com.user.grpc.UserService.LocProofRep) obj;

      boolean result = true;
      result = result && getProof()
          .equals(other.getProof());
      result = result && getProofDigSig()
          .equals(other.getProofDigSig());
      result = result && (getWitnessID()
          == other.getWitnessID());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
      hash = (37 * hash) + PROOF_DIG_SIG_FIELD_NUMBER;
      hash = (53 * hash) + getProofDigSig().hashCode();
      hash = (37 * hash) + WITNESSID_FIELD_NUMBER;
      hash = (53 * hash) + getWitnessID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.user.grpc.UserService.LocProofRep parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofRep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofRep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.LocProofRep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.user.grpc.UserService.LocProofRep prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocProofRep}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocProofRep)
        com.user.grpc.UserService.LocProofRepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.user.grpc.UserService.internal_static_LocProofRep_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.user.grpc.UserService.internal_static_LocProofRep_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.user.grpc.UserService.LocProofRep.class, com.user.grpc.UserService.LocProofRep.Builder.class);
      }

      // Construct using com.user.grpc.UserService.LocProofRep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        proof_ = "";

        proofDigSig_ = "";

        witnessID_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.user.grpc.UserService.internal_static_LocProofRep_descriptor;
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofRep getDefaultInstanceForType() {
        return com.user.grpc.UserService.LocProofRep.getDefaultInstance();
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofRep build() {
        com.user.grpc.UserService.LocProofRep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.user.grpc.UserService.LocProofRep buildPartial() {
        com.user.grpc.UserService.LocProofRep result = new com.user.grpc.UserService.LocProofRep(this);
        result.proof_ = proof_;
        result.proofDigSig_ = proofDigSig_;
        result.witnessID_ = witnessID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.user.grpc.UserService.LocProofRep) {
          return mergeFrom((com.user.grpc.UserService.LocProofRep)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.user.grpc.UserService.LocProofRep other) {
        if (other == com.user.grpc.UserService.LocProofRep.getDefaultInstance()) return this;
        if (!other.getProof().isEmpty()) {
          proof_ = other.proof_;
          onChanged();
        }
        if (!other.getProofDigSig().isEmpty()) {
          proofDigSig_ = other.proofDigSig_;
          onChanged();
        }
        if (other.getWitnessID() != 0) {
          setWitnessID(other.getWitnessID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.user.grpc.UserService.LocProofRep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.user.grpc.UserService.LocProofRep) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object proof_ = "";
      /**
       * <code>string proof = 2;</code>
       */
      public java.lang.String getProof() {
        java.lang.Object ref = proof_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proof_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proof = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProofBytes() {
        java.lang.Object ref = proof_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proof_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proof = 2;</code>
       */
      public Builder setProof(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proof = 2;</code>
       */
      public Builder clearProof() {
        
        proof_ = getDefaultInstance().getProof();
        onChanged();
        return this;
      }
      /**
       * <code>string proof = 2;</code>
       */
      public Builder setProofBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proof_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object proofDigSig_ = "";
      /**
       * <code>string proof_dig_sig = 3;</code>
       */
      public java.lang.String getProofDigSig() {
        java.lang.Object ref = proofDigSig_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proofDigSig_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proof_dig_sig = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProofDigSigBytes() {
        java.lang.Object ref = proofDigSig_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proofDigSig_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proof_dig_sig = 3;</code>
       */
      public Builder setProofDigSig(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proofDigSig_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proof_dig_sig = 3;</code>
       */
      public Builder clearProofDigSig() {
        
        proofDigSig_ = getDefaultInstance().getProofDigSig();
        onChanged();
        return this;
      }
      /**
       * <code>string proof_dig_sig = 3;</code>
       */
      public Builder setProofDigSigBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proofDigSig_ = value;
        onChanged();
        return this;
      }

      private int witnessID_ ;
      /**
       * <code>int32 witnessID = 5;</code>
       */
      public int getWitnessID() {
        return witnessID_;
      }
      /**
       * <code>int32 witnessID = 5;</code>
       */
      public Builder setWitnessID(int value) {
        
        witnessID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 witnessID = 5;</code>
       */
      public Builder clearWitnessID() {
        
        witnessID_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocProofRep)
    }

    // @@protoc_insertion_point(class_scope:LocProofRep)
    private static final com.user.grpc.UserService.LocProofRep DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.user.grpc.UserService.LocProofRep();
    }

    public static com.user.grpc.UserService.LocProofRep getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocProofRep>
        PARSER = new com.google.protobuf.AbstractParser<LocProofRep>() {
      @java.lang.Override
      public LocProofRep parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocProofRep(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocProofRep> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocProofRep> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.user.grpc.UserService.LocProofRep getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 X = 1;</code>
     */
    int getX();

    /**
     * <code>int32 Y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code Position}
   */
  public  static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.user.grpc.UserService.internal_static_Position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.user.grpc.UserService.internal_static_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.user.grpc.UserService.Position.class, com.user.grpc.UserService.Position.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>int32 X = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>int32 Y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.user.grpc.UserService.Position)) {
        return super.equals(obj);
      }
      com.user.grpc.UserService.Position other = (com.user.grpc.UserService.Position) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.user.grpc.UserService.Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.user.grpc.UserService.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.user.grpc.UserService.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.user.grpc.UserService.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Position)
        com.user.grpc.UserService.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.user.grpc.UserService.internal_static_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.user.grpc.UserService.internal_static_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.user.grpc.UserService.Position.class, com.user.grpc.UserService.Position.Builder.class);
      }

      // Construct using com.user.grpc.UserService.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.user.grpc.UserService.internal_static_Position_descriptor;
      }

      @java.lang.Override
      public com.user.grpc.UserService.Position getDefaultInstanceForType() {
        return com.user.grpc.UserService.Position.getDefaultInstance();
      }

      @java.lang.Override
      public com.user.grpc.UserService.Position build() {
        com.user.grpc.UserService.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.user.grpc.UserService.Position buildPartial() {
        com.user.grpc.UserService.Position result = new com.user.grpc.UserService.Position(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.user.grpc.UserService.Position) {
          return mergeFrom((com.user.grpc.UserService.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.user.grpc.UserService.Position other) {
        if (other == com.user.grpc.UserService.Position.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.user.grpc.UserService.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.user.grpc.UserService.Position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>int32 X = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 X = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 X = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 Y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 Y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Position)
    }

    // @@protoc_insertion_point(class_scope:Position)
    private static final com.user.grpc.UserService.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.user.grpc.UserService.Position();
    }

    public static com.user.grpc.UserService.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @java.lang.Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.user.grpc.UserService.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocProofReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocProofReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocProofRep_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocProofRep_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userService.proto\"X\n\013LocProofReq\022\020\n\010pr" +
      "overID\030\001 \001(\005\022\r\n\005epoch\030\002 \001(\005\022\026\n\003loc\030\003 \001(\013" +
      "2\t.Position\022\020\n\010dig_sign\030\004 \001(\t\"F\n\013LocProo" +
      "fRep\022\r\n\005proof\030\002 \001(\t\022\025\n\rproof_dig_sig\030\003 \001" +
      "(\t\022\021\n\twitnessID\030\005 \001(\005\" \n\010Position\022\t\n\001X\030\001" +
      " \001(\005\022\t\n\001Y\030\002 \001(\0052A\n\013userService\0222\n\024reques" +
      "tLocationProof\022\014.LocProofReq\032\014.LocProofR" +
      "epB\017\n\rcom.user.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LocProofReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocProofReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocProofReq_descriptor,
        new java.lang.String[] { "ProverID", "Epoch", "Loc", "DigSign", });
    internal_static_LocProofRep_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LocProofRep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocProofRep_descriptor,
        new java.lang.String[] { "Proof", "ProofDigSig", "WitnessID", });
    internal_static_Position_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Position_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
